# Generated by Django 3.2.2 on 2021-05-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_tv_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Show',
        ),
    ]
