# Generated by Django 3.2.2 on 2021-05-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_tv_app', '0002_rename_movie_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
